### ISSUE TITLE
using pulumi aviatrix 0.0.11

### ISSUE THREAD

**Issue by mohammedbanabila** [astipkovits/pulumi-aviatrix#3]
****this error come  when using pulumi aviatrix  at python ,        Type                           Name                    Plan       Info
 +   pulumi:pulumi:Stack            lab-aviatrix2-east1dev  create     1 message
     └─ aviatrix:index:AviatrixVpc  spoke1vpc1                         1 error
Diagnostics:
  pulumi:pulumi:Stack (lab-aviatrix2-east1dev):
    time="2024-05-16T18:34:25+03:00" level=info msg="Parsed Aviatrix login: [secret]"
  aviatrix:index:AviatrixVpc (spoke1vpc1):
    error: 1 error occurred:
        * controller version validation failed: current Terraform branch does not support controller version: UserConnect-7.1. Please go to 'https://registry.terraform.io/providers/AviatrixSystems/aviatrix/latest/docs/guides/release-compatibility' for version construct instructions

**Comment by astipkovits** [comment]
This Pulumi provider is based on the Aviatrix Terraform provider version 2.24.1. This version is compatible with Aviatrix controller version 6.9.161. Your controller is version 7.1.x which is not supported by this Pulumi provider, thus you see this message. For reference, see the Controller compatibility part of the readme.

**Comment by astipkovits** [comment]
Please note the this Pulumi provider is currently not under active development, so it will not support newer controller versions for now.

**Comment by mohammedbanabila** [comment]
thanks for response
